services:
  core-api:
    build:
      context: .
    environment:
      CORE_API_SERVER_PORT: ${CORE_API_SERVER_PORT}
      CORE_API_MYSQL_URL: ${CORE_API_MYSQL_URL}
      CORE_API_MYSQL_USERNAME: ${CORE_API_MYSQL_USERNAME}
      CORE_API_MYSQL_PASSWORD: ${CORE_API_MYSQL_PASSWORD}
      CORE_API_ADMIN_USERNAME: ${CORE_API_ADMIN_USERNAME}
      CORE_API_ADMIN_PASSWORD_HASH: ${CORE_API_ADMIN_PASSWORD_HASH}
      CORE_API_JWT_SECRET: ${CORE_API_JWT_SECRET}
      CORE_API_JWT_TTL_SECONDS: ${CORE_API_JWT_TTL_SECONDS}
      CORE_API_COOKIE_SECURE: ${CORE_API_COOKIE_SECURE}
      CORE_API_SCRAPPER_API_URL: ${CORE_API_SCRAPPER_API_URL}
    ports:
      - "${CORE_API_HOST_PORT}:${CORE_API_SERVER_PORT}"
