services:
  translation-service:
    build:
      context: .
    environment:
      TRANSLATION_SERVICE_SERVER_PORT: ${TRANSLATION_SERVICE_SERVER_PORT}
      TRANSLATION_SERVICE_LOCALES_PATH: ${TRANSLATION_SERVICE_LOCALES_PATH}
    ports:
      - "${TRANSLATION_SERVICE_HOST_PORT}:${TRANSLATION_SERVICE_SERVER_PORT}"
