spring.application.name=core-api
server.port=${CORE_API_SERVER_PORT}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

server.port=${CORE_API_SERVER_PORT}
spring.datasource.url=${CORE_API_MYSQL_URL}
spring.datasource.username=${CORE_API_MYSQL_USERNAME}
spring.datasource.password=${CORE_API_MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

app.auth.admin-username=${CORE_API_ADMIN_USERNAME}
app.auth.admin-password-hash=${CORE_API_ADMIN_PASSWORD_HASH}
app.auth.jwt-secret=${CORE_API_JWT_SECRET}
app.auth.jwt-ttl-seconds=${CORE_API_JWT_TTL_SECONDS}
app.scraper-api-url=${CORE_API_SCRAPPER_API_URL}
app.url-protection-secret=${SCRAPPER_URL_PROTECTION_SECRET}
