services:
  download-worker:
    build:
      context: .
    environment:
      DOWNLOAD_WORKER_SERVER_PORT: ${DOWNLOAD_WORKER_SERVER_PORT}
      RABBITMQ_HOST: ${DOWNLOAD_WORKER_RABBITMQ_HOST}
      MINIO_ENDPOINT: ${DOWNLOAD_WORKER_MINIO_ENDPOINT}
    ports:
      - "${DOWNLOAD_WORKER_HOST_PORT}:${DOWNLOAD_WORKER_SERVER_PORT}"
